= Complex Numbers

= Complex Numbers

Emmy provides comprehensive support for complex numbers through the `emmy.complex` namespace. This namespace offers functions and constructors for working with complex numbers in Clojure and ClojureScript, and integrates complex numbers into Emmy's generic arithmetic system.

== Creating Complex Numbers

You can create complex numbers using the `complex` function:

[source,clojure]
----
(require '[emmy.complex :as c])

(c/complex 1 2)        ; => #emmy/complex [1 2]
(c/complex "1.2+3.4i") ; => #emmy/complex "1.2+3.4i"
(c/complex [1 2])      ; => #emmy/complex [1 2]
----

== Constants

The namespace provides several useful constants:

[source,clojure]
----
c/ZERO ; Complex zero (0 + 0i)
c/ONE  ; Complex one (1 + 0i)
c/I    ; Imaginary unit (0 + 1i)
c/-I   ; Negative imaginary unit (0 - 1i)
----

== Arithmetic Operations

Complex numbers support all standard arithmetic operations:

[source,clojure]
----
(require '[emmy.generic :as g])

(g/add (c/complex 1 2) (c/complex 3 4))  ; => #emmy/complex [4 6]
(g/sub (c/complex 1 2) (c/complex 3 4))  ; => #emmy/complex [-2 -2]
(g/mul (c/complex 1 2) (c/complex 3 4))  ; => #emmy/complex [-5 10]
(g/div (c/complex 1 2) (c/complex 3 4))  ; => #emmy/complex [0.44 0.08]
----

== Trigonometric and Hyperbolic Functions

Emmy supports a wide range of trigonometric and hyperbolic functions for complex numbers:

[source,clojure]
----
(g/sin (c/complex 0.1 0.2))  ; => #emmy/complex "0.101836749421+0.200330161149I"
(g/cos (c/complex 0.1 0.2))  ; => #emmy/complex "1.0149706707-0.0201000610277I"
(g/tan (c/complex 0.1 0.2))  ; => #emmy/complex "0.0963881308565+0.19928415106I"

(g/sinh (c/complex 0.1 0.2)) ; => #emmy/complex "0.0981700839054+0.199663505514I"
(g/cosh (c/complex 0.1 0.2)) ; => #emmy/complex "0.984970995703+0.0199000611944I"
(g/tanh (c/complex 0.1 0.2)) ; => #emmy/complex "0.103721150028+0.200614484227I"
----

Inverse trigonometric and hyperbolic functions are also available:

[source,clojure]
----
(g/asin (c/complex 0.1 0.2)) ; => #emmy/complex "0.0981975111335+0.19963938539I"
(g/acos (c/complex 0.1 0.2)) ; => #emmy/complex "1.47259881566-0.19963938539I"
(g/atan (c/complex 0.1 0.2)) ; => #emmy/complex "0.103748113218+0.200586618131I"

(g/asinh (c/complex 0.1 0.2)) ; => #emmy/complex "0.10186391598+0.200303571099I"
(g/acosh (c/complex 0.1 0.2)) ; => #emmy/complex "0.19963938539+1.47259881566I"
(g/atanh (c/complex 0.1 0.2)) ; => #emmy/complex "0.096415620203+0.199261222833I"
----

== Other Mathematical Functions

Emmy provides various other mathematical functions for complex numbers:

[source,clojure]
----
(g/sqrt (c/complex 1 2))     ; => #emmy/complex [1.272019649514 0.7861513777574]
(g/exp (g/mul c/I Math/PI))  ; => #emmy/complex [-1 1.2246467991474E-16]
(g/log (c/complex 1 2))      ; => #emmy/complex [0.8047189562170859 1.1071487177940904]
----

== Gaussian Integers

Emmy supports Gaussian integers, which are complex numbers with integer real and imaginary parts:

[source,clojure]
----
(c/round (c/complex 1.2 3.7)) ; => #emmy/complex [1 4]
----

== Complex GCD

Emmy provides a function to compute the Greatest Common Divisor (GCD) of complex numbers:

[source,clojure]
----
(g/gcd (c/complex 24 2) 12) ; => #emmy/complex [0 2]
----

Note that the GCD of two complex numbers is determined up to a factor of ±1 and ±i.

== Generic Function Support

Complex numbers in Emmy support a wide range of generic functions, including:

- Arithmetic operations (`g/add`, `g/sub`, `g/mul`, `g/div`)
- Comparison (`g/zero?`, `g/one?`, `g/identity?`)
- Mathematical functions (`g/abs`, `g/magnitude`, `g/angle`, `g/conjugate`)
- Trigonometric and hyperbolic functions
- Rounding functions (`g/floor`, `g/ceiling`)

This extensive support allows complex numbers to be used seamlessly with Emmy's generic arithmetic system.

